github:
    features:
        wiki: true
        issues: true
        merge: true
        projects: true
notifications:
    commits:      commits@dubbo.apache.org
    issues:       notifications@dubbo.apache.org
    pullrequests: notifications@dubbo.apache.org
    jira_options: link label link label
