language: golang

sudo: required
go:
  - 1.13
env:
  - GO111MODULE=on
script:
  - ./start_integrate_test.sh
#  - helloworld/dubbo/.travis.yml
#  - direct/dubbo/.travis.yml
#  - async/.travis.yml
#  - metric/dubbo/.travis.yml
