language: golang

sudo: required
go:
  - 1.13
env:
  - GO111MODULE=on
import:
  - helloworld/dubbo/.travis.yml
  - direct/dubbo/.travis.yml
  - async/.travis.yml
  - metric/dubbo/.travis.yml
  - filter/custom_filter/dubbo/.travis.yml
  - configcenter/apollo/dubbo/.travis.yml
  - configcenter/zookeeper/dubbo/.travis.yml
  - configcenter/nacos/dubbo/.travis.yml
